"""Remove is_active

Revision ID: 7cdb4b3f2c5b
Revises: 8166c17956f7
Create Date: 2024-05-08 19:56:53.790632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cdb4b3f2c5b'
down_revision: Union[str, None] = '8166c17956f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
